export const HOME_DATA = [
    {
        id: 1,
        GOODS_CATEGORY: "100원 상품",
        GOODS_NO: 0,
        IMG_URL: 'http://image.lottesuper.co.kr/static-root/image/gigagenie/lhstest/static/media/papertowel.png',
        KEYWORD: '첫 구매 프로모션',
    },
    {
        id: 2,
        GOODS_CATEGORY: '전단상품',
        GOODS_NO: 0,
        IMG_URL: 'http://image.lottesuper.co.kr/static-root/image/gigagenie/lhstest/static/media/catalog_goods.png',
        KEYWORD: '매장',
        PRIORITY_RANK: 2
    },
    {
        id: 3,
        GOODS_CATEGORY: '자주 사는 상품',
        GOODS_NO: 0,
        IMG_URL: 'http://image.lottesuper.co.kr/static-root/image/gigagenie/lhstest/static/media/frequent_goods.png',
        KEYWORD: '매장',
        PRIORITY_RANK: 3
    },
    {
        id: 4,
        GOODS_CATEGORY: '인기상품',
        GOODS_NO: 0,
        IMG_URL: 'http://image.lottesuper.co.kr/static-root/image/gigagenie/lhstest/static/media/famous_goods.png',
        KEYWORD: '매장',
        PRIORITY_RANK: 4
    },
    {
        id: 5,
        GOODS_CATEGORY: '우유',
        GOODS_NO: 1047134,
        IMG_URL: 'http://image.lottesuper.co.kr/static-root/image/gigagenie/lhstest/static/media/milk.png',
        KEYWORD: '검색',
        PRIORITY_RANK: 1
    },
    {
        id: 6,
        GOODS_CATEGORY: '계란',
        GOODS_NO: 1394336,
        IMG_URL: 'http://image.lottesuper.co.kr/static-root/image/gigagenie/lhstest/static/media/eggs.png',
        KEYWORD: '검색',
        PRIORITY_RANK: 2
    },
    {
        id: 7,
        GOODS_CATEGORY: '라면',
        GOODS_NO: 1058104,
        IMG_URL: 'http://image.lottesuper.co.kr/static-root/image/gigagenie/lhstest/static/media/ramen.png',
        KEYWORD: '검색',
        PRIORITY_RANK: 3
    },
    {
        id: 8,
        GOODS_CATEGORY: '요구르트',
        GOODS_NO: 1372640,
        IMG_URL: 'http://image.lottesuper.co.kr/static-root/image/gigagenie/lhstest/static/media/yogrut.png',
        KEYWORD: '검색',
        PRIORITY_RANK: 4
    },
    {
        id: 9,
        GOODS_CATEGORY: '생수',
        GOODS_NO: 1249877,
        IMG_URL: 'http://image.lottesuper.co.kr/static-root/image/gigagenie/lhstest/static/media/water.png',
        KEYWORD: '검색',
        PRIORITY_RANK: 5
    },
    {
        id: 10,
        GOODS_CATEGORY: '쌀',
        GOODS_NO: 1345328,
        IMG_URL: 'http://image.lottesuper.co.kr/static-root/image/gigagenie/lhstest/static/media/rice.png',
        KEYWORD: '검색',
        PRIORITY_RANK: 6
    },
    {
        id: 11,
        GOODS_CATEGORY: '햇반',
        GOODS_NO: 1400502,
        IMG_URL: 'http://image.lottesuper.co.kr/static-root/image/gigagenie/lhstest/static/media/instant_rice.png',
        KEYWORD: '검색',
        PRIORITY_RANK: 7
    },
    {
        id: 12,
        GOODS_CATEGORY: '치즈',
        GOODS_NO: 1384688,
        IMG_URL: 'http://image.lottesuper.co.kr/static-root/image/gigagenie/lhstest/static/media/cheeze.png',
        KEYWORD: '검색',
        PRIORITY_RANK: 8
    },
    {
        id: 13,
        GOODS_CATEGORY: '커피',
        GOODS_NO: 1282029,
        IMG_URL: 'http://image.lottesuper.co.kr/static-root/image/gigagenie/lhstest/static/media/coffee.png',
        KEYWORD: '검색',
        PRIORITY_RANK: 9
    },
    {
        id: 14,
        GOODS_CATEGORY: '케찹',
        GOODS_NO: 1005619,
        IMG_URL: 'http://image.lottesuper.co.kr/static-root/image/gigagenie/lhstest/static/media/ketchup.png',
        KEYWORD: '검색',
        PRIORITY_RANK: 10
    },
    {
        id: 15,
        GOODS_CATEGORY: '당근',
        GOODS_NO: 1032252,
        IMG_URL: 'http://image.lottesuper.co.kr/static-root/image/gigagenie/lhstest/static/media/carrot.png',
        KEYWORD: '검색',
        PRIORITY_RANK: 11
    },
    {
        id: 16,
        GOODS_CATEGORY: '고등어',
        GOODS_NO: 1316370,
        IMG_URL: 'http://image.lottesuper.co.kr/70/63/31/1/1316370_1_200.jpg',
        KEYWORD: '검색',
        PRIORITY_RANK: 12
    },
    {
        id: 17,
        GOODS_CATEGORY: '돼지고기',
        GOODS_NO: 1014743,
        IMG_URL: 'http://image.lottesuper.co.kr/43/47/01/1/1014743_1_200.jpg',
        KEYWORD: '검색',
        PRIORITY_RANK: 13
    },
    {
        id: 18,
        GOODS_CATEGORY: '만두',
        GOODS_NO: 1332521,
        IMG_URL: 'http://image.lottesuper.co.kr/21/25/33/1/1332521_1_200.jpg',
        KEYWORD: '검색',
        PRIORITY_RANK: 14
    },
    {
        id: 19,
        GOODS_CATEGORY: '올리브유',
        GOODS_NO: 1305879,
        IMG_URL: 'http://image.lottesuper.co.kr/79/58/30/1/1305879_1_200.jpg',
        KEYWORD: '검색',
        PRIORITY_RANK: 15
    },
    {
        id: 20,
        GOODS_CATEGORY: '초콜릿',
        GOODS_NO: 1053613,
        IMG_URL: 'http://image.lottesuper.co.kr/13/36/05/1/1053613_1_200.jpg',
        KEYWORD: '검색',
        PRIORITY_RANK: 16
    },
    {
        id: 21,
        GOODS_CATEGORY: '견과류',
        GOODS_NO: 1383350,
        IMG_URL: 'http://image.lottesuper.co.kr/50/33/38/1/1383350_1_200.jpg',
        KEYWORD: '검색',
        PRIORITY_RANK: 17
    }
];

export const DETAIL_DATA = [
    {
        id: 1,
        GOODS_CATEGORY: '우유',
        GOODS_NM: '초L 세이브우유 930ML*2입기획',
        GOODS_NO: 1047134,
        IMG_URL: 'http://image.lottesuper.co.kr/34/71/04/1/1047134_1_400.jpg',
        DC_RATE: 17,
        TOP_REVIEW_CNT: 3247,
        REVIEW_SCORE: 9.9,
        LIST_PRICE: 3490,
        ORIGIN: '국산',
        COMPANY: '건국대학교건국유업',
        GOODS_SPEC: '930ML*2',
        PRIORITY_RANK: 1
    },
    {
        id: 2,
        GOODS_CATEGORY: '계란',
        GOODS_NM: '초L프레시)무항생제계란 (20입/대란)',
        GOODS_NO: 1394336,
        IMG_URL: 'http://image.lottesuper.co.kr/36/43/39/1/1394336_1_400.jpg',
        DC_RATE: 0,
        TOP_REVIEW_CNT: 2766,
        REVIEW_SCORE: 9.8,
        LIST_PRICE: 5490,
        ORIGIN: '국산',
        COMPANY: '(주)구구축산',
        GOODS_SPEC: '20입/대란',
        PRIORITY_RANK: 1
    },
    {
        id: 3,
        GOODS_CATEGORY: '라면',
        GOODS_NM: '농심 신라면 (120G*5입)',
        GOODS_NO: 1058104,
        IMG_URL: 'http://image.lottesuper.co.kr/04/81/05/1/1058104_1_400.jpg',
        DC_RATE: 7,
        TOP_REVIEW_CNT: 392,
        REVIEW_SCORE: 9.9,
        LIST_PRICE: 3380,
        ORIGIN: '면:호주산',
        COMPANY: '(주)농심',
        GOODS_SPEC: '120G*5',
        PRIORITY_RANK: 1
    },
    {
        id: 4,
        GOODS_CATEGORY: '요구르트',
        GOODS_NM: '[빙그레]빙그레 빅 요구르트 280ML',
        GOODS_NO: 1372640,
        IMG_URL: 'http://image.lottesuper.co.kr/40/26/37/1/1372640_1_400.jpg',
        DC_RATE: 5,
        TOP_REVIEW_CNT: 353,
        REVIEW_SCORE: 7.9,
        LIST_PRICE: 1000,
        ORIGIN: '수입산',
        COMPANY: '매일유업(주)',
        GOODS_SPEC: '280ML',
        PRIORITY_RANK: 1
    },
    {
        id: 5,
        GOODS_CATEGORY: '생수',
        GOODS_NM: '롯데 아이시스8.0 (2L*6개입)',
        GOODS_NO: 1249877,
        IMG_URL: 'http://image.lottesuper.co.kr/77/98/24/1/1249877_1_400.jpg',
        DC_RATE: 28,
        TOP_REVIEW_CNT: 2932,
        REVIEW_SCORE: 9.9,
        LIST_PRICE: 3600,
        ORIGIN: '국산',
        COMPANY: '롯데칠성음료(주)',
        GOODS_SPEC: '2L*6개입',
        PRIORITY_RANK: 1
    },
    {
        id: 6,
        GOODS_CATEGORY: '쌀',
        GOODS_NM: '[우리마을농협쌀]무농약 백미(4kg)',
        GOODS_NO: 1345328,
        IMG_URL: 'http://image.lottesuper.co.kr/28/53/34/1/1345328_1_400.jpg',
        DC_RATE: 24,
        TOP_REVIEW_CNT: 2,
        REVIEW_SCORE: 5.6,
        LIST_PRICE: 27000,
        ORIGIN: '국산',
        COMPANY: '전남친환경쌀클러스터',
        GOODS_SPEC: '4KG',
        PRIORITY_RANK: 1
    },
    {
        id: 7,
        GOODS_CATEGORY: '햇반',
        GOODS_NM: 'CJ 햇반 210G*6',
        GOODS_NO: 1400502,
        IMG_URL: 'http://image.lottesuper.co.kr/02/05/40/1/1400502_1_400.jpg',
        DC_RATE: 0,
        TOP_REVIEW_CNT: 760,
        REVIEW_SCORE: 9.9,
        LIST_PRICE: 7800,
        ORIGIN: '국산',
        COMPANY: '씨제이제일제당(주)',
        GOODS_SPEC: '210G*6',
        PRIORITY_RANK: 1
    },
    {
        id: 8,
        GOODS_CATEGORY: '치즈',
        GOODS_NM: '동원 체다치즈 클래식 204G',
        GOODS_NO: 1384688,
        IMG_URL: 'http://image.lottesuper.co.kr/88/46/38/1/1384688_1_400.jpg',
        DC_RATE: 55,
        TOP_REVIEW_CNT: 2321,
        REVIEW_SCORE: 8.8,
        LIST_PRICE: 4000,
        ORIGIN: '국내산,뉴질랜드산',
        COMPANY: '(주)동원에프앤비소와나무',
        GOODS_SPEC: '204G',
        PRIORITY_RANK: 1
    },
    {
        id: 9,
        GOODS_CATEGORY: '커피',
        GOODS_NM: '동서 맥심모카 (40T* 2+1 기획)',
        GOODS_NO: 1282029,
        IMG_URL: 'http://image.lottesuper.co.kr/29/20/28/1/1282029_1_400.jpg',
        DC_RATE: 14,
        TOP_REVIEW_CNT: 1236,
        REVIEW_SCORE: 7.7,
        LIST_PRICE: 13900,
        ORIGIN: '국산',
        COMPANY: '동서식품',
        GOODS_SPEC: '40T*2+1',
        PRIORITY_RANK: 1
    },
    {
        id: 10,
        GOODS_CATEGORY: '케찹',
        GOODS_NM: '[오뚜기]오뚜기 케찹 (500g)',
        GOODS_NO: 1005619,
        IMG_URL: 'http://image.lottesuper.co.kr/19/56/00/1/1005619_1_400.jpg',
        DC_RATE: 0,
        TOP_REVIEW_CNT: 119,
        REVIEW_SCORE: 10,
        LIST_PRICE: 2400,
        ORIGIN: '수입산',
        COMPANY: '(주)오뚜기',
        GOODS_SPEC: '500G',
        PRIORITY_RANK: 1
    },
    {
        id: 11,
        GOODS_CATEGORY: '당근',
        GOODS_NM: '흙당근(100G)',
        GOODS_NO: 1032252,
        IMG_URL: 'http://image.lottesuper.co.kr/52/22/03/1/1032252_1_400.jpg',
        DC_RATE: 4,
        TOP_REVIEW_CNT: 1180,
        REVIEW_SCORE: 9.5,
        LIST_PRICE: 499,
        ORIGIN: '국산',
        COMPANY: '백토영농조합법인',
        GOODS_SPEC: '100G (±10g)',
        PRIORITY_RANK: 1
    },
    {
        id: 12,
        GOODS_CATEGORY: '고등어',
        GOODS_NM: '[사조]사조 고등어(280G)',
        GOODS_NO: 1316370,
        IMG_URL: 'http://image.lottesuper.co.kr/70/63/31/1/1316370_1_400.jpg',
        DC_RATE: 8,
        TOP_REVIEW_CNT: 551,
        REVIEW_SCORE: 9.9,
        LIST_PRICE: 1990,
        ORIGIN: '국산',
        COMPANY: '사조산업(주)',
        GOODS_SPEC: '280G',
        PRIORITY_RANK: 1
    },
    {
        id: 13,
        GOODS_CATEGORY: '돼지고기',
        GOODS_NM: 'E-국내산 냉장 돈 목심 (구이용/100G)',
        GOODS_NO: 1014743,
        IMG_URL: 'http://image.lottesuper.co.kr/43/47/01/1/1014743_1_400.jpg',
        DC_RATE: 0,
        TOP_REVIEW_CNT: 1551,
        REVIEW_SCORE: 9.8,
        LIST_PRICE: 2480,
        ORIGIN: '국내산',
        COMPANY: '롯데푸드',
        GOODS_SPEC: '100G (±10g)',
        PRIORITY_RANK: 1
    },
    {
        id: 14,
        GOODS_CATEGORY: '만두',
        GOODS_NM: 'CJ 납작 바삭군만두 700G',
        GOODS_NO: 1332521,
        IMG_URL: 'http://image.lottesuper.co.kr/21/25/33/1/1332521_1_400.jpg',
        DC_RATE: 3,
        TOP_REVIEW_CNT: 1580,
        REVIEW_SCORE: 8.8,
        LIST_PRICE: 9980,
        ORIGIN: '국산,미국산,중국산',
        COMPANY: '(주)엄지식품',
        GOODS_SPEC: '700G',
        PRIORITY_RANK: 1
    },
    {
        id: 15,
        GOODS_CATEGORY: '올리브유',
        GOODS_NM: '[샘표]폰타나 올리브유 500ML',
        GOODS_NO: 1305879,
        IMG_URL: 'http://image.lottesuper.co.kr/79/58/30/1/1305879_1_400.jpg',
        DC_RATE: 10,
        TOP_REVIEW_CNT: 37,
        REVIEW_SCORE: 9.9,
        LIST_PRICE: 8900,
        ORIGIN: '이탈리아산',
        COMPANY: 'BASSO FEDELE',
        GOODS_SPEC: '500ML',
        PRIORITY_RANK: 1
    },
    {
        id: 16,
        GOODS_CATEGORY: '초콜릿',
        GOODS_NM: '롯데 ABC초콜릿 (200G)',
        GOODS_NO: 1053613,
        IMG_URL: 'http://image.lottesuper.co.kr/13/36/05/1/1053613_1_400.jpg',
        DC_RATE: 50,
        TOP_REVIEW_CNT: 973,
        REVIEW_SCORE: 10,
        LIST_PRICE: 4800,
        ORIGIN: '수입산',
        COMPANY: '롯데제과주식회사',
        GOODS_SPEC: '200G',
        PRIORITY_RANK: 1
    },
    {
        id: 17,
        GOODS_CATEGORY: '견과류',
        GOODS_NM: '구운 아몬드 (500G/봉)',
        GOODS_NO: 1383350,
        IMG_URL: 'http://image.lottesuper.co.kr/50/33/38/1/1383350_1_400.jpg',
        DC_RATE: 10,
        TOP_REVIEW_CNT: 92,
        REVIEW_SCORE: 9.8,
        LIST_PRICE: 14900,
        ORIGIN: '미국산',
        COMPANY: '나라통상(주)',
        GOODS_SPEC: '봉',
        PRIORITY_RANK: 1
    },
    {
        id: 18,
        GOODS_CATEGORY: '우유',
        GOODS_NM: '남양 맛있는우유 GT기획(1L*2입)',
        GOODS_NO: 1218069,
        IMG_URL: 'http://image.lottesuper.co.kr/69/80/21/1/1218069_1_400.jpg',
        DC_RATE: 5,
        TOP_REVIEW_CNT: 4390,
        REVIEW_SCORE: 9.9,
        LIST_PRICE: 4680,
        ORIGIN: '국산',
        COMPANY: '(주)남양유업',
        GOODS_SPEC: '1L*2입',
        PRIORITY_RANK: 2
    },
    {
        id: 19,
        GOODS_CATEGORY: '우유',
        GOODS_NM: '푸르밀 고칼슘 저지방우유 900ML*2입기획',
        GOODS_NO: 1054331,
        IMG_URL: 'http://image.lottesuper.co.kr/31/43/05/1/1054331_1_400.jpg',
        DC_RATE: 24,
        TOP_REVIEW_CNT: 2377,
        REVIEW_SCORE: 9.8,
        LIST_PRICE: 4500,
        ORIGIN: '국산',
        COMPANY: '롯데우유주식회사',
        GOODS_SPEC: '900ML*2입',
        PRIORITY_RANK: 3
    },
    {
        id: 20,
        GOODS_CATEGORY: '우유',
        GOODS_NM: '매일 저지방우유(1%)1L',
        GOODS_NO: 1009641,
        IMG_URL: 'http://image.lottesuper.co.kr/41/96/00/1/1009641_1_400.jpg',
        DC_RATE: 10,
        TOP_REVIEW_CNT: 179,
        REVIEW_SCORE: 9.9,
        LIST_PRICE: 2600,
        ORIGIN: '국산',
        COMPANY: '매일유업(주)',
        GOODS_SPEC: '1L',
        PRIORITY_RANK: 4
    },
    {
        id: 21,
        GOODS_CATEGORY: '우유',
        GOODS_NM: '[서울]서울목장저지방우유 (1L)',
        GOODS_NO: 1013683,
        IMG_URL: 'http://image.lottesuper.co.kr/83/36/01/1/1013683_1_400.jpg',
        DC_RATE: 10,
        TOP_REVIEW_CNT: 246,
        REVIEW_SCORE: 9.8,
        LIST_PRICE: 3060,
        ORIGIN: '국산',
        COMPANY: '서울우유',
        GOODS_SPEC: '1000ML',
        PRIORITY_RANK: 5
    },
    {
        id: 22,
        GOODS_CATEGORY: '우유',
        GOODS_NM: '파스퇴르 후레쉬우유 (1.8L)',
        GOODS_NO: 1005969,
        IMG_URL: 'http://image.lottesuper.co.kr/69/59/00/1/1005969_1_400.jpg',
        DC_RATE: 10,
        TOP_REVIEW_CNT: 1594,
        REVIEW_SCORE: 9.9,
        LIST_PRICE: 5380,
        ORIGIN: '국산',
        COMPANY: '(주)롯데삼강',
        GOODS_SPEC: '1.8L',
        PRIORITY_RANK: 6
    },
    {
        id: 23,
        GOODS_CATEGORY: '우유',
        GOODS_NM: '목우촌 우유 900ML',
        GOODS_NO: 1370047,
        IMG_URL: 'http://image.lottesuper.co.kr/47/00/37/1/1370047_1_400.jpg',
        DC_RATE: 7,
        TOP_REVIEW_CNT: 452,
        REVIEW_SCORE: 9.9,
        LIST_PRICE: 2100,
        ORIGIN: '국산',
        COMPANY: '부산우유농협',
        GOODS_SPEC: '900ML',
        PRIORITY_RANK: 7
    },
    {
        id: 24,
        GOODS_CATEGORY: '우유',
        GOODS_NM: '[매일]매일 상하 유기농 저지방우유 750ML',
        GOODS_NO: 1011054,
        IMG_URL: 'http://image.lottesuper.co.kr/54/10/01/1/1011054_1_400.jpg',
        DC_RATE: 10,
        TOP_REVIEW_CNT: 34,
        REVIEW_SCORE: 9.8,
        LIST_PRICE: 4850,
        ORIGIN: '국산',
        COMPANY: '매일유업(주)',
        GOODS_SPEC: '750ML',
        PRIORITY_RANK: 8
    },
    {
        id: 25,
        GOODS_CATEGORY: '우유',
        GOODS_NM: '일동 후디스 순우유 저지방 750ML',
        GOODS_NO: 1366243,
        IMG_URL: 'http://image.lottesuper.co.kr/43/62/36/1/1366243_1_400.jpg',
        DC_RATE: 19,
        TOP_REVIEW_CNT: 43,
        REVIEW_SCORE: 9.7,
        LIST_PRICE: 3070,
        ORIGIN: '국산',
        COMPANY: '일동후디스(주)',
        GOODS_SPEC: '750ML',
        PRIORITY_RANK: 9
    },
    {
        id: 26,
        GOODS_CATEGORY: '우유',
        GOODS_NM: '일동 초유우유 930ML',
        GOODS_NO: 1397154,
        IMG_URL: 'http://image.lottesuper.co.kr/54/71/39/1/1397154_1_400.jpg',
        DC_RATE: 15,
        TOP_REVIEW_CNT: 98,
        REVIEW_SCORE: 9.8,
        LIST_PRICE: 3840,
        ORIGIN: '국산',
        COMPANY: '일동후디스(주)',
        GOODS_SPEC: '930ML',
        PRIORITY_RANK: 10
    },
    {
        id: 27,
        GOODS_CATEGORY: '우유',
        GOODS_NM: '[남양]남양 고소한저지방기획 900ML*2',
        GOODS_NO: 1370148,
        IMG_URL: 'http://image.lottesuper.co.kr/48/01/37/1/1370148_1_400.jpg',
        DC_RATE: 10,
        TOP_REVIEW_CNT: 429,
        REVIEW_SCORE: 9.9,
        LIST_PRICE: 4480,
        ORIGIN: '국산',
        COMPANY: '남양유업(주)',
        GOODS_SPEC: '900ML*2',
        PRIORITY_RANK: 11
    },
    {
        id: 28,
        GOODS_CATEGORY: '계란',
        GOODS_NM: '초L프레시)무항생제 계란 (30입/특란)',
        GOODS_NO: 1362894,
        IMG_URL: 'http://image.lottesuper.co.kr/94/28/36/1/1362894_1_400.jpg',
        DC_RATE: 10,
        TOP_REVIEW_CNT: 3811,
        REVIEW_SCORE: 7.9,
        LIST_PRICE: 4990,
        ORIGIN: '국산',
        COMPANY: '농업회사밥인 조인(주)',
        GOODS_SPEC: '30입',
        PRIORITY_RANK: 2
    },
    {
        id: 29,
        GOODS_CATEGORY: '라면',
        GOODS_NM: '농심 올리브짜파게티 140G*5+1입 증정기획',
        GOODS_NO: 1060397,
        IMG_URL: 'http://image.lottesuper.co.kr/97/03/06/1/1060397_1_400.jpg',
        DC_RATE: 10,
        TOP_REVIEW_CNT: 3705,
        REVIEW_SCORE: 9.9,
        LIST_PRICE: 3890,
        ORIGIN: '수입산',
        COMPANY: '(주)농심',
        GOODS_SPEC: '140G*5',
        PRIORITY_RANK: 2
    },
    {
        id: 30,
        GOODS_CATEGORY: '라면',
        GOODS_NM: '오뚜기 진라면 매운맛 120G*5입',
        GOODS_NO: 1005588,
        IMG_URL: 'http://image.lottesuper.co.kr/88/55/00/1/1005588_1_400.jpg',
        DC_RATE: 10,
        TOP_REVIEW_CNT: 3644,
        REVIEW_SCORE: 9.9,
        LIST_PRIEC: 2850,
        ORIGIN: '수입산',
        COMPANY: '(주)오뚜기',
        GOODS_SPEC: '120G*5',
        PRIORITY_RANK: 3
    },
    {
        id: 31,
        GOODS_CATEGORY: '라면',
        GOODS_NM: '[오뚜기]오뚜기 스낵면 108G*5입',
        GOODS_NO: 1005549,
        IMG_URL: 'http://image.lottesuper.co.kr/49/55/00/1/1005549_1_400.jpg',
        DC_RATE: 10,
        TOP_REVIEW_CNT: 2895,
        REVIEW_SCORE: 9.9,
        LIST_PRICE: 3050,
        ORIGIN: '수입산',
        COMPANY: '(주)오뚜기',
        GOODS_SPEC: '108G*5',
        PRIORITY_RANK: 4
    },
    {
        id: 32,
        GOODS_CATEGORY: '라면',
        GOODS_NM: '[삼양]삼양 컵라면 (65G)',
        GOODS_NO: 1005281,
        IMG_URL: 'http://image.lottesuper.co.kr/81/52/00/1/1005281_1_400.jpg',
        DC_RATE: 10,
        TOP_REVIEW_CNT: 69,
        REVIEW_SCORE: 9.9,
        LIST_PRICE: 850,
        ORIGIN: '수입산',
        COMPANY: '삼양식품(주)',
        GOODS_SPEC: '65G',
        PRIORITY_RANK: 5
    },
    {
        id: 33,
        GOODS_CATEGORY: '라면',
        GOODS_NM: '[오뚜기]오뚜기 라면사리 (110G)',
        GOODS_NO: 1005542,
        IMG_URL: 'http://image.lottesuper.co.kr/42/55/00/1/1005542_1_400.jpg',
        DC_RATE: 10,
        TOP_REVIEW_CNT: 327,
        REVIEW_SCORE: 9.9,
        LIST_PRICE: 390,
        ORIGIN: '수입산',
        COMPANY: '(주)오뚜기',
        GOODS_SPEC: '110G',
        PRIORITY_RANK: 6
    },
    {
        id: 34,
        GOODS_CATEGORY: '요구르트',
        GOODS_NM: '빙그레 요플레클래식 플레인 85G*4입',
        GOODS_NO: 1005255,
        IMG_URL: 'http://image.lottesuper.co.kr/55/52/00/1/1005255_1_400.jpg',
        DC_RATE: 45,
        TOP_REVIEW_CNT: 3490,
        REVIEW_SCORE: 9.9,
        LIST_PRICE: 2800,
        ORIGIN: '국산, 네덜란드산',
        COMPANY: '(주)빙그레',
        GOODS_SPEC: '85G*4',
        PRIORITY_RANK: 2
    },
    {
        id: 35,
        GOODS_CATEGORY: '생수',
        GOODS_NM: '제주 삼다수 2L*6입',
        GOODS_NO: 1249491,
        IMG_URL: 'http://image.lottesuper.co.kr/91/94/24/1/1249491_1_400.jpg',
        DC_RATE: 10,
        TOP_REVIEW_CNT: 3055,
        REVIEW_SCORE: 9.9,
        LIST_PRICE: 5640,
        ORIGIN: '국내산',
        COMPANY: '제주특별자치도개발공사',
        GOODS_SPEC: '2L*6입',
        PRIORITY_RANK: 2
    },
    {
        id: 36,
        GOODS_CATEGORY: '쌀',
        GOODS_NM: '[17년 햅쌀] Lgrow 찰진쌀 10KG/포',
        GOODS_NO: 1378420,
        IMG_URL: 'http://image.lottesuper.co.kr/20/84/37/1/1378420_1_400.jpg',
        DC_RATE: 10,
        TOP_REVIEW_CNT: 138,
        REVIEW_SCORE: 9.7,
        LIST_PRICE: 30900,
        ORIGIN: '국산',
        COMPANY: '롯데상사(주)',
        GOODS_SPEC: '10KG/포',
        PRIORITY_RANK: 2
    },
    {
        id: 37,
        GOODS_CATEGORY: '햇반',
        GOODS_NM: '[CJ]CJ 햇반 발아 현미밥 (210G*4입+2입)',
        GOODS_NO: 1260115,
        IMG_URL: 'http://image.lottesuper.co.kr/15/01/26/1/1260115_1_400.jpg',
        DC_RATE: 10,
        TOP_REVIEW_CNT: 283,
        REVIEW_SCORE: 9.9,
        LIST_PRICE: 6990,
        ORIGIN: '국산',
        COMPANY: '씨제이제일제당(주)',
        GOODS_SPEC: '210g*4입+2입',
        PRIORITY_RANK: 2
    },
    {
        id: 38,
        GOODS_CATEGORY: '치즈',
        GOODS_NM: '동원 고칼슘치즈 180G',
        GOODS_NO: 1039672,
        IMG_URL: 'http://image.lottesuper.co.kr/72/96/03/1/1039672_1_400.jpg',
        DC_RATE: 47,
        TOP_REVIEW_CNT: 1590,
        REVIEW_SCORE: 9.9,
        LIST_PRICE: 4600,
        ORIGIN: '국산',
        COMPANY: '(주)동원에프앤비',
        GOODS_SPEC: '180G',
        PRIORITY_RANK: 2
    },
    {
        id: 39,
        GOODS_CATEGORY: '커피',
        GOODS_NM: '롯데 칸타타 프리미엄라떼 (275ML)',
        GOODS_NO: 1007985,
        IMG_URL: 'http://image.lottesuper.co.kr/85/79/00/1/1007985_1_400.jpg',
        DC_RATE: 43,
        TOP_REVIEW_CNT: 576,
        REVIEW_SCORE: 9.9,
        LIST_PRICE: 1770,
        ORIGIN: '수입산',
        COMPANY: '롯데칠성음료(주)',
        GOODS_SPEC: '275ML',
        PRIORITY_RANK: 2
    },
    {
        id: 40,
        GOODS_CATEGORY: '케찹',
        GOODS_NM: '[대상]청정원 진한 토마토 케찹 300g',
        GOODS_NO: 1004794,
        IMG_URL: 'http://image.lottesuper.co.kr/94/47/00/1/1004794_1_400.jpg',
        DC_RATE: 10,
        TOP_REVIEW_CNT: 453,
        REVIEW_SCORE: 9.9,
        LIST_PRICE: 1500,
        ORIGIN: '중국산',
        COMPANY: '대상(주)',
        GOODS_SPEC: '300G',
        PRIORITY_RANK: 2
    },
    {
        id: 41,
        GOODS_CATEGORY: '당근',
        GOODS_NM: '당근(기획) 1KG/봉',
        GOODS_NO: 1339592,
        IMG_URL: 'http://image.lottesuper.co.kr/92/95/33/1/1339592_1_400.jpg',
        DC_RATE: 10,
        TOP_REVIEW_CNT: 578,
        REVIEW_SCORE: 9.9,
        LIST_PRICE: 3990,
        ORIGIN: '국내산',
        COMPANY: '백토영농조합법인',
        GOODS_SPEC: '1KG/봉',
        PRIORITY_RANK: 2
    },
    {
        id: 42,
        GOODS_CATEGORY: '고등어',
        GOODS_NM: '고등어자반 (특/2마리/손)_냉동',
        GOODS_NO: 1001992,
        IMG_URL: 'http://image.lottesuper.co.kr/92/19/00/1/1001992_1_400.jpg',
        DC_RATE: 10,
        TOP_REVIEW_CNT: 310,
        REVIEW_SCORE: 9.7,
        LIST_PRICE: 3990,
        ORIGIN: '국산',
        COMPANY: '등푸른식품',
        GOODS_SPEC: '특',
        PRIORITY_RANK: 2
    },
    {
        id: 43,
        GOODS_CATEGORY: '돼지고기',
        GOODS_NM: 'E-국내산 냉장 돈갈비 찜용 100G',
        GOODS_NO: 1014774,
        IMG_URL: 'http://image.lottesuper.co.kr/74/47/01/1/1014774_1_400.jpg',
        DC_RATE: 10,
        TOP_REVIEW_CNT: 1007,
        REVIEW_SCORE: 9.7,
        LIST_PRICE: 1590,
        ORIGIN: '국내산',
        COMPANY: '롯데햄',
        GOODS_SPEC: '100G (±10g)',
        PRIORITY_RANK: 2
    },
    {
        id: 44,
        GOODS_CATEGORY: '만두',
        GOODS_NM: '[풀무원]풀무원 생물만두(250G*3개)',
        GOODS_NO: 1030615,
        IMG_URL: 'http://image.lottesuper.co.kr/15/06/03/1/1030615_1_400.jpg',
        DC_RATE: 8,
        TOP_REVIEW_CNT: 541,
        REVIEW_SCORE: 9.9,
        LIST_PRICE: 8200,
        ORIGIN: '국산',
        COMPANY: '풀무원',
        GOODS_SPEC: '250G*3',
        PRIORITY_RANK: 2
    },
    {
        id: 45,
        GOODS_CATEGORY: '올리브유',
        GOODS_NM: '오뚜기 프레스코 올리브유 900ML',
        GOODS_NO: 1005631,
        IMG_URL: 'http://image.lottesuper.co.kr/31/56/00/1/1005631_1_400.jpg',
        DC_RATE: 10,
        TOP_REVIEW_CNT: 196,
        REVIEW_SCORE: 9.8,
        LIST_PRICE: 12600,
        ORIGIN: '스페인산',
        COMPANY: '오뚜기',
        GOODS_SPEC: '900ML',
        PRIORITY_RANK: 2
    },
    {
        id: 46,
        GOODS_CATEGORY: '초콜릿',
        GOODS_NM: '롯데 가나 에어라이트 33G',
        GOODS_NO: 1405006,
        IMG_URL: 'http://image.lottesuper.co.kr/06/50/40/1/1405006_1_400.jpg',
        DC_RATE: 10,
        TOP_REVIEW_CNT: 9,
        REVIEW_SCORE: 9.9,
        LIST_PRICE: 960,
        ORIGIN: '외국산',
        COMPANY: '롯데제과(주)',
        GOODS_SPEC: '33G',
        PRIORITY_RANK: 2
    },
    {
        id: 47,
        GOODS_CATEGORY: '견과류',
        GOODS_NM: '카카오닙스 200G',
        GOODS_NO: 1387780,
        IMG_URL: 'http://image.lottesuper.co.kr/80/77/38/1/1387780_1_400.jpg',
        DC_RATE: 28,
        TOP_REVIEW_CNT: 47,
        REVIEW_SCORE: 9.9,
        LIST_PRICE: 6990,
        ORIGIN: '페루',
        COMPANY: '(주)길림양행',
        GOODS_SPEC: '200G',
        PRIORITY_RANK: 2
    }
];